package com.prod.bbsys.model.pojo;

import java.io.Serializable;

public class Staff implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.staff_id
     *
     * @mbggenerated
     */
    private Integer staffId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.staff_name
     *
     * @mbggenerated
     */
    private String staffName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.staff_tel
     *
     * @mbggenerated
     */
    private String staffTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.staff_eamil
     *
     * @mbggenerated
     */
    private String staffEamil;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.staff_bankNum
     *
     * @mbggenerated
     */
    private String staffBanknum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table staff
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.staff_id
     *
     * @return the value of staff.staff_id
     *
     * @mbggenerated
     */
    public Integer getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.staff_id
     *
     * @param staffId the value for staff.staff_id
     *
     * @mbggenerated
     */
    public void setStaffId(Integer staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.user_id
     *
     * @return the value of staff.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.user_id
     *
     * @param userId the value for staff.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.staff_name
     *
     * @return the value of staff.staff_name
     *
     * @mbggenerated
     */
    public String getStaffName() {
        return staffName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.staff_name
     *
     * @param staffName the value for staff.staff_name
     *
     * @mbggenerated
     */
    public void setStaffName(String staffName) {
        this.staffName = staffName == null ? null : staffName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.staff_tel
     *
     * @return the value of staff.staff_tel
     *
     * @mbggenerated
     */
    public String getStaffTel() {
        return staffTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.staff_tel
     *
     * @param staffTel the value for staff.staff_tel
     *
     * @mbggenerated
     */
    public void setStaffTel(String staffTel) {
        this.staffTel = staffTel == null ? null : staffTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.staff_eamil
     *
     * @return the value of staff.staff_eamil
     *
     * @mbggenerated
     */
    public String getStaffEamil() {
        return staffEamil;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.staff_eamil
     *
     * @param staffEamil the value for staff.staff_eamil
     *
     * @mbggenerated
     */
    public void setStaffEamil(String staffEamil) {
        this.staffEamil = staffEamil == null ? null : staffEamil.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.staff_bankNum
     *
     * @return the value of staff.staff_bankNum
     *
     * @mbggenerated
     */
    public String getStaffBanknum() {
        return staffBanknum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.staff_bankNum
     *
     * @param staffBanknum the value for staff.staff_bankNum
     *
     * @mbggenerated
     */
    public void setStaffBanknum(String staffBanknum) {
        this.staffBanknum = staffBanknum == null ? null : staffBanknum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Staff other = (Staff) that;
        return (this.getStaffId() == null ? other.getStaffId() == null : this.getStaffId().equals(other.getStaffId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getStaffName() == null ? other.getStaffName() == null : this.getStaffName().equals(other.getStaffName()))
            && (this.getStaffTel() == null ? other.getStaffTel() == null : this.getStaffTel().equals(other.getStaffTel()))
            && (this.getStaffEamil() == null ? other.getStaffEamil() == null : this.getStaffEamil().equals(other.getStaffEamil()))
            && (this.getStaffBanknum() == null ? other.getStaffBanknum() == null : this.getStaffBanknum().equals(other.getStaffBanknum()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getStaffId() == null) ? 0 : getStaffId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getStaffName() == null) ? 0 : getStaffName().hashCode());
        result = prime * result + ((getStaffTel() == null) ? 0 : getStaffTel().hashCode());
        result = prime * result + ((getStaffEamil() == null) ? 0 : getStaffEamil().hashCode());
        result = prime * result + ((getStaffBanknum() == null) ? 0 : getStaffBanknum().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", staffId=").append(staffId);
        sb.append(", userId=").append(userId);
        sb.append(", staffName=").append(staffName);
        sb.append(", staffTel=").append(staffTel);
        sb.append(", staffEamil=").append(staffEamil);
        sb.append(", staffBanknum=").append(staffBanknum);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}