package com.prod.bbsys.model.pojo;

import java.io.Serializable;

public class Storage extends StorageKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage.storage_amount
     *
     * @mbggenerated
     */
    private Integer storageAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage.storage_pay
     *
     * @mbggenerated
     */
    private Float storagePay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table storage
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage.storage_amount
     *
     * @return the value of storage.storage_amount
     *
     * @mbggenerated
     */
    public Integer getStorageAmount() {
        return storageAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage.storage_amount
     *
     * @param storageAmount the value for storage.storage_amount
     *
     * @mbggenerated
     */
    public void setStorageAmount(Integer storageAmount) {
        this.storageAmount = storageAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage.storage_pay
     *
     * @return the value of storage.storage_pay
     *
     * @mbggenerated
     */
    public Float getStoragePay() {
        return storagePay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage.storage_pay
     *
     * @param storagePay the value for storage.storage_pay
     *
     * @mbggenerated
     */
    public void setStoragePay(Float storagePay) {
        this.storagePay = storagePay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Storage other = (Storage) that;
        return (this.getGoodsId() == null ? other.getGoodsId() == null : this.getGoodsId().equals(other.getGoodsId()))
            && (this.getSupplierId() == null ? other.getSupplierId() == null : this.getSupplierId().equals(other.getSupplierId()))
            && (this.getStorageDate() == null ? other.getStorageDate() == null : this.getStorageDate().equals(other.getStorageDate()))
            && (this.getStorageAmount() == null ? other.getStorageAmount() == null : this.getStorageAmount().equals(other.getStorageAmount()))
            && (this.getStoragePay() == null ? other.getStoragePay() == null : this.getStoragePay().equals(other.getStoragePay()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getGoodsId() == null) ? 0 : getGoodsId().hashCode());
        result = prime * result + ((getSupplierId() == null) ? 0 : getSupplierId().hashCode());
        result = prime * result + ((getStorageDate() == null) ? 0 : getStorageDate().hashCode());
        result = prime * result + ((getStorageAmount() == null) ? 0 : getStorageAmount().hashCode());
        result = prime * result + ((getStoragePay() == null) ? 0 : getStoragePay().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", storageAmount=").append(storageAmount);
        sb.append(", storagePay=").append(storagePay);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}