package com.prod.bbsys.model.pojo;

import java.io.Serializable;
import java.util.Date;

public class StorageKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage.goods_id
     *
     * @mbggenerated
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage.supplier_id
     *
     * @mbggenerated
     */
    private Integer supplierId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage.storage_date
     *
     * @mbggenerated
     */
    private Date storageDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table storage
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage.goods_id
     *
     * @return the value of storage.goods_id
     *
     * @mbggenerated
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage.goods_id
     *
     * @param goodsId the value for storage.goods_id
     *
     * @mbggenerated
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage.supplier_id
     *
     * @return the value of storage.supplier_id
     *
     * @mbggenerated
     */
    public Integer getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage.supplier_id
     *
     * @param supplierId the value for storage.supplier_id
     *
     * @mbggenerated
     */
    public void setSupplierId(Integer supplierId) {
        this.supplierId = supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage.storage_date
     *
     * @return the value of storage.storage_date
     *
     * @mbggenerated
     */
    public Date getStorageDate() {
        return storageDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage.storage_date
     *
     * @param storageDate the value for storage.storage_date
     *
     * @mbggenerated
     */
    public void setStorageDate(Date storageDate) {
        this.storageDate = storageDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        StorageKey other = (StorageKey) that;
        return (this.getGoodsId() == null ? other.getGoodsId() == null : this.getGoodsId().equals(other.getGoodsId()))
            && (this.getSupplierId() == null ? other.getSupplierId() == null : this.getSupplierId().equals(other.getSupplierId()))
            && (this.getStorageDate() == null ? other.getStorageDate() == null : this.getStorageDate().equals(other.getStorageDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getGoodsId() == null) ? 0 : getGoodsId().hashCode());
        result = prime * result + ((getSupplierId() == null) ? 0 : getSupplierId().hashCode());
        result = prime * result + ((getStorageDate() == null) ? 0 : getStorageDate().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", goodsId=").append(goodsId);
        sb.append(", supplierId=").append(supplierId);
        sb.append(", storageDate=").append(storageDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}